package com.auth.enums;

public enum ErrorCode {
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    OAUTH_STATE_MISMATCH,
    OAUTH_TOKEN_EXCHANGE_FAILED,
    OAUTH_USER_INFO_FAILED
}
